### get the data
```{r}
library(stringr)
library(missForest)
library(ggplot2)


meta_and_type = read.delim("../DATA/metadata_eng_lineage.tsv")
meta_and_type$damage = as.numeric(meta_and_type$damage)

ctype_df = read.delim("../DATA/mgx_cluster_deblur_genus_narmT_prev0.1det5_6.tsv", sep = " ")

colnames(ctype_df) = c("mgx_specimen", "ctype")
meta_and_type = merge(meta_and_type, ctype_df, by = "mgx_specimen")

mt <- meta_and_type
mt = mt[,-1]
mt$date = as.numeric(str_sub(mt$date,6,7))
mt$ctype = as.factor(mt$ctype)
```

### statistical tests for numerical variables
```{r}
numcols=c('age','oxygen.saturation', 'respiratory.rate',
       'heart.rate', 'blood.pressure.d.', 'blood.pressure.s.',
       'temperature','date', 'damage')
numcols %in% colnames(mt)
chis = list()
for(col in numcols){
  l = data.frame(rt = as.factor(paste("rt",mt$ctype)), val = mt[,col])
  print(col)
  k = kruskal.test(val ~ rt, data =  l)
  chis[[col]]=k$p.value
}

vchis=unlist(chis)
names(vchis) = c('age','oxygen saturation', 'respiratory rate',
       'heart rate', 'blood pressure (d)', 'blood pressure (s)',
       'temperature','month', 'lung damage')
vchis = vchis[order(-vchis)]
#names(vchis)=

names(vchis) =gsub("\\..+","",names(vchis))
par(mar=c(4,11,4,4), lty = 0);barplot(-log10(vchis), las = 2, main = "numerical variables", col = "gray70", xlab = "-log10(pvalue)", cex.lab = 1.3, horiz = T)
```

### statistical tests for categorical variables
```{r}
catcols=c('hospital.id', 'inpatient', 'is.concious', 'additional_O2',  'sex', 'obesity', 'smoking', 'smoking_before', 'diabetes', 'COPD', 'IBD', 'arthritis', 'tuberculosis', 'hypertension', 'coronary.artery.disease', 'chronic.heart.failure', 'asthma', 'city',  'lineage', 'KT')
pis = list()
for(col in catcols){
  
  l = data.frame(rt = as.factor(paste("rt",mt$ctype)), val = mt[,col])
  w =  dcast(l,rt ~ val)
  w=w[,-1]
  #print(w)
  f = chisq.test(w)
  pis[[col]]=f$p.value
}

vpis=unlist(pis)
names(vpis) = c('hospital id', 'inpatient', 'is concious', 'additional O2',  'sex', 'obesity', 'smoking', 'smoking before', 'diabetes', 'COPD', 'IBD', 'arthritis', 'tuberculosis', 'hypertension', 'coronary artery disease', 'chronic heart failure', 'asthma', 'city',  'virus lineage', 'KT score')
vpis = vpis[order(-vpis)]
#names(vchis)=

names(vpis) =gsub("\\..+","",names(vpis))

par(mar=c(4,11,4,4), lty = 0);barplot(-log10(vpis), las = 2, main = "categorical variables", col = "gray70", xlab = "-log10(pvalue)", cex.lab = 1.3, horiz = T)

```


## Association of Community type with age. 
```{r}

library("rstatix")
library("ggpubr")

l = data.frame(ctype = mt$ctype, age = mt$age)

stat.test.dunn <- l %>% dunn_test(age ~ ctype, p.adjust.method = "hochberg") 
stat.test.dunn <- stat.test.dunn %>% add_xy_position(x = "ctype")

ggplot(l, aes(x=ctype, y=age), cex= 1.5)  + geom_boxplot(fill="gray90",col="gray50", outlier.size = 0) +geom_jitter(shape=16, position=position_jitter(0.1), col="dodgerblue4")+  theme_bw()+ theme(text = element_text(size=16)) +
  stat_pvalue_manual(stat.test.dunn, hide.ns = T) + labs(x="community type"); 
```
## Association of Community type with month.
```{r}


l = data.frame(ctype = mt$ctype, month = mt$date)

library("rstatix")
library("ggpubr")
stat.test.dunn <- l %>% dunn_test(month ~ ctype, p.adjust.method = "hochberg") 
stat.test.dunn <- stat.test.dunn %>% add_xy_position(x = "ctype")

ggplot(l, aes(x=ctype, y=month), cex= 1.5)  + geom_boxplot(fill="gray90",col="gray50", outlier.size = 0) +geom_jitter(shape=16, position=position_jitter(0.1), col="dodgerblue4")+  theme_bw()+ theme(text = element_text(size=16)) +
  stat_pvalue_manual(stat.test.dunn, hide.ns = T) + labs(x="community type"); 
```

## Association of Community type with city of sampling.
```{r}
l = data.frame(ctype = mt$ctype, city = mt$city)
pvals = list()
sig = 0.05
for(c in levels(as.factor(l$city))){
  for(c2 in levels(as.factor(l$city))){
      if(c2 == c) next
      l. = subset(l, l$city == c)
      l.other = subset(l, l$city == c2)
      
      ft = fisher.test(rbind(table(l.$ctype),table(l.other$ctype)),simulate.p.value=TRUE)
      pval = ft$p.value
      pvals[[paste(c, c2)]] = pval
  }
}
p.adjust(pvals)
```
## Association of Community type with city of sampling. Heatmap
```{r}
library(pheatmap)
l = data.frame(ctype = mt$ctype, city = mt$city, inpatient=mt$inpatient)
l = l[complete.cases(l),]
cit = dcast(l, ctype ~ city+inpatient)
rownames(cit) = cit$ctype
cit = cit[,-1]
### remove categories with low number of patients:
cit = cit[,-which(colSums(cit)<10)]

colnames(cit) = gsub("_1"," (outpatients)", colnames(cit))
colnames(cit) = gsub("_2"," (inpatients)", colnames(cit))

pheatmap(t(cit), scale = "row", cluster_cols = F, fontsize = 14)



```


```{r}
l = data.frame(rt = mt$ctype, hr = mt$heart_rate)
p <- ggplot(l, aes(x=rt, y=hr), cex= 1.5)+ylim(50, 110)  + geom_boxplot(fill="gray90",col="gray50") +geom_jitter(shape=16, position=position_jitter(0.1), col="dodgerblue4")+ ggtitle("ЧСС")+ theme_bw()+ theme(text = element_text(size=16)); p

l = data.frame(rt = mt$ctype, mnth = mt$date)
p <- ggplot(l, aes(x=rt, y=mnth)) + geom_boxplot(); p

l = data.frame(rt = mt$ctype, mnth = mt$date)
p <- ggplot(l, aes(x=rt, y=mnth))  + geom_jitter(shape=16, position=position_jitter(0.2)); p

l = data.frame(rt = mt$ctype, mnth = mt$date)
p <- ggplot(l, aes(x=rt, y=mnth))  + geom_jitter(shape=16, position=position_jitter(0.2)); p
# geom_dotplot(binaxis='y', stackdir='center', dotsize=0.4)

l = data.frame(rt = mt$ctype, val = mt$temperature)
p <- ggplot(l, aes(x=rt, y=val))  + geom_boxplot(fill="gray90",col="gray50") +geom_jitter(shape=16, position=position_jitter(0.1), col="dodgerblue4")+ ggtitle("temperature")+ theme_bw()+ theme(text = element_text(size=16)); p
# geom_dotplot(binaxis='y', stackdir='center', outsize=0.4)

```

### Random Forest Variable Importance
```{r, fig.width = 14}
mt <-  meta_and_type
mt = mt[,-1]
mt$date = as.numeric(str_sub(mt$date,6,7))
library(randomForest)
mt$ctype = as.factor(mt$ctype)
rf = randomForest(formula = ctype~ . , data = mt,ntree=3000, na.action =  na.roughfix, 
                  importance=TRUE, strata=T)
varImpPlot(rf)
```
```{r}
phylo_obj <-  read_rds('../DATA/phyloseq.rds')
meta = data.frame(sample_data(phylo_obj))
respirotype_df = read.delim("../DATA/mgx_cluster_deblur_genus_narmT_prev0.1det5_6.tsv", sep = " ")
colnames(respirotype_df) = c("mgx_specimen", "respirotype")
meta_and_type = merge(meta, respirotype_df, by = "mgx_specimen")
```


