---
title: "make figure1"
output: html_notebook
---


### get the data
```{r}
meta16s = read.delim("../DATA/metadata_eng_lineage.tsv")
meta16s$sample = rownames(meta16s)

covid_ru = read.delim("../DATA/COVID_Yandex.csv")
colnames(covid_ru) = c("date_ym", "new_cases")
covid_ru$date_ym = substr(covid_ru$date_ym, 1, 7 )

meta = subset(meta, sapply(as.character(meta$date), nchar) >= 7) 
meta$date_ym = substr(meta$date,1,7)
month_table_vector = table(meta$date_ym)
month_table_vector = c(month_table_vector, "2021-02"=0)
```
### make plot
```{r}
library("reshape2")
month_table = data.frame(date_ym = names(month_table_vector), samples = month_table_vector)
month_table = merge(month_table, covid_ru, all.x = T)
month_city = dcast(meta, "date_ym ~ city")
month_city = as.matrix(month_city)
month = month_city[,1]
rownames(month_city) = month
month_city = month_city[,-1]

barplot(t(as.matrix(month_city)), ylim = c(0,200),  las = 2,col=c("brown", 
         "orange", "seagreen", "royalblue"), border = NA); lines(x = br, month_table$new_cases/10000, type = "l", col = "black", lwd = 3); points(x = br, month_table$new_cases/10000,  col = "gray50", pch = 18, cex = 0.8); legend("topright",c("new cases in Russia", colnames(month_city)), fill = c("black","brown", "orange", "seagreen", "royalblue"),bty='n')
```

